### ISSUE TITLE
New methods

### ISSUE THREAD

**Issue by frontsideair** [tov/disjoint-sets-rs#1]
I want to use this library but I need some methods. I'll try to implement them this weekend if I have spare time. Naming can be improved.

- `fn len_of_union(&self, element: Element) -> usize`: Length of the union that this element belongs to.
- `fn unions_of_size_one(&self) -> Vec<Element>`: Elements that are not in a union with anything else. This is not crucial as they can be kept in a Set and removed when a union is made.

**Comment by tov** [comment]
Huh, interesting. Thanks for opening the issue. From what I can tell, `len_of_union` can be implemented in terms of the the existing API:

```rust
fn len_of_union<Element: ElementType>(uf: &UnionFind<Element>, a: Element) -> usize {
    let mut result = 0;
    for b in 0 .. uf.len() {
        if uf.equiv(a, Element::from_usize(b).unwrap()) {
            result += 1;
        }
    }
   result
}
```

That should be `O(n log* n)`. I don't think you can do better by putting it inside the abstraction boundary.

As for `unions_of_size_one`, you can do it in `O(n log* n)` as well, in terms of the current API:

```rust
fn unions_of_size_one<Element: ElementType>(uf: &UnionFind<Element>) -> Vec<Element> {
    let mut remaining: HashSet<usize> = (0 .. uf.len()).collect();

    for i in 0 .. uf.len() {
        let element = Element::from_usize(i).unwrap();
        let root = uf.find(element);
        if element != root {
            remaining.remove(&i);
        }
    }

    remaining.into_iter().flat_map(Element::from_usize).collect()
}
```

Given that these operations seem to be not too hard to express in terms of the existing API, and that moving them into the API would not offer any performance benefits, I'm not sure it's worth adding them to the library. That said, I'm open to further persuasion.

**Comment by frontsideair** [comment]
Thanks for taking the time for doing the actual implementations. I agree that these helpers aren't interesting enough to add to the library. A higher level abstraction with a builtin `HashSet` could be a better approach, without cluttering the well known Union-Find.
